<?php

namespace OC\UserBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function myFindDQL($id)
    {
        $query = $this->_em->createQuery('SELECT a FROM OCUserBundle:User a WHERE a.id = :id');
        $query->setParameter('id', $id);

        // Utilisation de getSingleResult car la requête ne doit retourner qu'un seul résultat
        return $query->getSingleResult();
    }

    public function findByUser($user)
    {
        $qb = $this->createQueryBuilder('a');

        $qb->where('a.user = :user')
            ->setParameter('user', $user)
        ;

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }

    public function myFindAll()
    {
        return $this
            ->createQueryBuilder('a')
            ->getQuery()
            ->getResult()
            ;
    }
}
