<?php

namespace OC\ProjectBundle\Repository;

/**
 * AjaxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AjaxRepository extends \Doctrine\ORM\EntityRepository
{
}
