<?php

namespace OC\ProjectBundle\Repository;

/**
 * BookmarksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookmarksRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByUser($userBook)
    {
        $qb = $this->createQueryBuilder('a');

        $qb->where('a.userBook = :userBook')
            ->setParameter('userBook', $userBook)
        ;

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }

    public function myFindAll()
    {
        return $this
            ->createQueryBuilder('a')
            ->getQuery()
            ->getResult()
            ;
    }
}
