<?php

namespace OC\ProjectBundle\Repository;

/**
 * ProjetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjetRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByUser($userProjet)
    {
        $qb = $this->createQueryBuilder('a');

        $qb->where('a.userProjet = :userProjet')
            ->setParameter('userProjet', $userProjet)
            ->setFirstResult(0)
            ->setMaxResults(10)
        ;

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }

    public function myFindAll()
    {
        return $this
            ->createQueryBuilder('a')
            ->getQuery()
            ->getResult()
            ;
    }
}
